project:
  type: website

website:
  title: "Radiology ML Tutorials"
  site-url: https://radml.wfwiggins.com
  description: "Interactive tutorials for AI applications in radiology"
  favicon: logo.png
  navbar:
    left: 
      - setup.qmd
      - advanced-setup.qmd
      - resources.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wfwiggins
      - icon: twitter
        href: https://twitter.com/walterfwiggins
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
